### ISSUE TITLE
snap insists on using swrast and cannot start

### ISSUE THREAD

**Issue by Deminarcis** [libretro/retroarch-snap#12]
I have a new install of Ubuntu 18.04 and the snap for Retroarch wont start.

When running from the terminal the error is:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libEGL warning: DRI2: failed to authenticate
Segmentation fault (core dumped)
```

I am using NVIDIA proprietary drivers with a GTX970 on Xorg (GPU drivers dont work with Wayland)

**Comment by hizzlekizzle** [comment]
I believe this is an issue related to the Nvidia proprietary driver and the container/sandbox format. There's a similar issue here:
https://github.com/gnome-mpv/gnome-mpv/issues/310

I don't think there's anything we can do about it, unfortunately.

**Comment by Deminarcis** [comment]
no problem, just tested on an non-NVIDIA machine and the snap works fine. thanks for answering :+1:
