### ISSUE TITLE
 Ubuntu 18.04, can't load PPSSPP core.

### ISSUE THREAD

**Issue by tabetai** [libretro/retroarch-snap#15]
I get this error when trying to load ppsspp core:
```
[ERROR] Failed to open libretro core:"/home/username/snap/retroarch/120/.config/retroarch/cores/ppsspp_libretro.so" 
[ERROR] Error(s): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by hizzlekizzle** [comment]
Looks like it's trying to link against a system lib for SDL, which isn't included in the snap package. I'm not really sure why not, though, so I'll look into adding it to the package.

**Comment by tabetai** [comment]
It works now. Thanks!
