### ISSUE TITLE
Dolphin core won't load.

### ISSUE THREAD

**Issue by tabetai** [libretro/retroarch-snap#17]
```
[ERROR] Error(s): libcurl.so.4: cannot open shared object file: No such file or directory
```
libcurl4 is missing, apparently.

**Comment by hizzlekizzle** [comment]
I added libcurl to the edge build, but I don't think it gets dolphin running, unfortunately.

I'm not going to be able to add all of the dependencies required by every core. Really, it's the core/maintainer's responsibility to get rid of as many external dependencies as possible, either by eliminating them or baking them into the core. We don't want the snap to balloon in size because we're trying to pack in everything any core might potentially need.

**Comment by kaincenteno** [comment]
I got the following running it on the current version:

retroarch 
/usr/share/libdrm/amdgpu.ids: No such file or directory
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
/usr/share/libdrm/amdgpu.ids: No such file or directory
X Error:  BadMatch
  Request Major code 152 (GLX)
  Request Minor code 26 ()
  Error Serial #68
  Current Serial #68
malloc_consolidate(): invalid chunk size
Aborted (core dumped)

**Comment by gouchi** [comment]
@kaincenteno please check #32 thank you.

**Comment by jkilpe** [comment]
I get following error on the latest stable version

[ERROR] Failed to open libretro core: "/home/jkilp/snap/retroarch/423/.config/retroarch/cores/dolphin_libretro.so"
Error(s): /snap/retroarch/423/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/jkilp/snap/retroarch/42[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.

**Comment by hizzlekizzle** [comment]
yes, this is a known mismatch between the system building the snaps (based on xenial) and the one in our infrastructure that's building the libs (based on bionic). It will resolve itself relatively soon, once the snapcraft infrastructure dumps xenial for bionic.

**Comment by hizzlekizzle** [comment]
This should be fixed now in the edge channel

**Comment by gouchi** [comment]
@tabetai @jkilpe Please reply so that we can close this issue if it is fixed. Thank you.

**Comment by jkilpe** [comment]
Issue is fixed, works well.
