### ISSUE TITLE
Unable to use controller

### ISSUE THREAD

**Issue by extraymond** [libretro/retroarch-snap#2]
Hi! I've trouble setting up controller(steam controller and logitech F310).
It's detected under lsusb.

**Comment by hizzlekizzle** [comment]
When you plug them in, does it say "blahblah controller not configured"? if so, you may not have any autoconfig profiles, which is what RetroArch uses to detect and automatically map gamepads. You can fetch the profiles from the online updater, but you probably want to go to settings > directory and make sure the autoconfig directory is pointing somewhere sensible and user-writeable first.

**Comment by extraymond** [comment]
Hi! Currently I tried using the remap function in input control, but 
nothing happens when I press on the buttons.

hizzlekizzle 於 2017年09月28日 22:32 寫道:

**Comment by gouchi** [comment]
Hi,

The autoconfig profiles is packaged and you can updated with the online updater.

Thank you.

Kind regards,

**Comment by gouchi** [comment]
Also you can try 

```
sudo snap connect retroarch:raw-usb
sudo snap connect retroarch:joystick
```
[Source](https://forums.libretro.com/t/retroarch-wont-see-logitech-f310-controller-using-xinput-ubuntu/15005/2)

**Comment by extraymond** [comment]
Hi! I've had success with the updated version.

I noticed that if I want to use steam controller, I have to launch steam first, else the controller is not initialized.

**Comment by gouchi** [comment]
Thank for the feedback.

**Comment by epl692** [comment]
I was having an issue with a reproduction snes controller, sudo snap connect retroarch:joystick cleared up the issue.
