### ISSUE TITLE
Fresh installation of 1.7.6 won't launch

### ISSUE THREAD

**Issue by futwick** [libretro/retroarch-snap#21]
Fresh installation, when I try to launch version 1.7.6 I get the following error:

`mkdir: cannot create directory ‘/home/my-username/snap/retroarch’: Read-only file system`

The folder exists, it is created when I first try to launch the retroarch snap.

**Comment by hizzlekizzle** [comment]
I'm not sure what's going on here. We haven't changed anything of consequence for a long time, but it's happening here, too. It works fine updating an existing installation but a new install gets the error :/

**Comment by ghisvail** [comment]
Same issue here.

**Comment by hizzlekizzle** [comment]
@futwick @ghisvail can you guys try it again?

**Comment by futwick** [comment]
thanks @hizzlekizzle, I tried a fresh installation from the _edge_ channel, a new error message:

`/snap/retroarch/183/bin/desktop-launch: line 546: /snap/retroarch/183/usr/local/bin/retroarch-wrapper: No such file or directory`

**Comment by hizzlekizzle** [comment]
gah, that was a dumb typo. If you're on a amd64 device, can you try updating to edge one more time?

**Comment by futwick** [comment]
yes, it works (and there is audio!)

thank you @hizzlekizzle

**Comment by hizzlekizzle** [comment]
@futwick oh nice! I didn't expect the audio to be fixed, too, so that's a bonus!

Thanks for testing, I'll get this build pushed up to the stable, etc. branches.
