### ISSUE TITLE
1.7.6 no audio

### ISSUE THREAD

**Issue by Vailure** [libretro/retroarch-snap#22]
snap 1.7.6 no audio no matter the setting/core

**Comment by hizzlekizzle** [comment]
I think this should be fixed now if you update to the latest package, so I'm going to close the issue, but feel free to reopen if it persists.

**Comment by CamJRP** [comment]
I installed this version of retroarch via apt-get, not snap.
Suddenly there is no sound in any game, without having make any change in cfg.

**Comment by hizzlekizzle** [comment]
@CamJRP Can you pastebin a log?

**Comment by acc3ssd** [comment]
I installed Retroarch via the snap package today and I'm not getting any audio, no matter what driver I use. Is there something I'm supposed to do to fix this? (I'm running Ubuntu 18.04.)

**Comment by hizzlekizzle** [comment]
@acc3ssd Not that I know of. Can you post a log? launch from a commandline like this:
retroarch --menu --verbose > ~/log.txt
and then post the output somewhere like pastebin.com and post a link here.

**Comment by acc3ssd** [comment]
I'm getting the following errors on stdout:

ALSA lib conf.c:3750:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

Here's the log: https://pastebin.com/XNtZKucR

**Comment by hizzlekizzle** [comment]
Seems to be related to:
https://forum.snapcraft.io/t/spotify-does-not-play-audio/3266/17
I'm not altogether sure what to make of that thread, though. I'm assuming [this](https://forum.snapcraft.io/t/spotify-does-not-play-audio/3266/17) needs to be added somewhere...
