### ISSUE TITLE
Slow init

### ISSUE THREAD

**Issue by Armiixteryx** [libretro/retroarch-snap#26]
When I run RetroArch, it takes so much time to open (approx. 30 secs).

Checking process with `htop` I get this process running every time before RetroArch UI shows on screen:

`update-mime-database.real /home/armiixteryx/snap/retroarch/210/.local/share/mime`

**Comment by gouchi** [comment]
Or maybe [Xbox one controller connected by bluetooth](https://github.com/libretro/RetroArch/issues/10408) ?

**Comment by Armiixteryx** [comment]
No, I had none of those controllers.
Unfortunately I am not using a distro with snap anymore :/

**Comment by hizzlekizzle** [comment]
Ok, we'll close this issue for now, then, and if someone else has it we'll reopen it.
