### ISSUE TITLE
Suppress screensaver not working. Dbus connect needed?

### ISSUE THREAD

**Issue by cbagpipe** [libretro/retroarch-snap#30]
OS: Kubuntu 19.10 with Plasma 5.6.15 and Xorg
Snap: Retroarch stable  1.8.0-332

When playing with joystick, screen dims and then turns off by timers, set in system power management settings. As was told here - [https://github.com/libretro/RetroArch/issues/7472](https://github.com/libretro/RetroArch/issues/7472), i think snap needs dbus connection...

**Comment by hizzlekizzle** [comment]
From the snap documentation, it doesn't seem that we are allowed to automatically hook up dbus: https://snapcraft.io/docs/dbus-interface

**Comment by cbagpipe** [comment]
So, I don't even see `dbus `in available interfaces to connent it manually in _snapcraft.yaml_. And the is no `--enable-dbus` in config parameters.

**Comment by hizzlekizzle** [comment]
eyy, nice! I just added it, so it should show up in the 'edge' channel soon. Let me know if it works and I'll promote that build to the other channels, as well.

**Comment by cbagpipe** [comment]
Just checked, and it's not working. Really, before replying I spent some time to figure out - how snap interfaces works. And I can't... I don't think it should work like "I added plug in .yaml and it should work". Point me, where to find exact architecture of how .yaml definition affects core and snap... some hooks called maybe? I don't know...

**Comment by hizzlekizzle** [comment]
AFAIK, for auto-connected plugs, that should be all it takes. However, even if I manually connect the plug, the screen is still going to sleep, so I'm wondering if something might be wrong with the screen-inhibit-control interface...

**Comment by hizzlekizzle** [comment]
@cbagpipe can you try the latest edge build? I added a dbus dependency and forced it to --enable-dbus, in addition to having the plug, in case we needed to do some more on the RetroArch side of things.

**Comment by cbagpipe** [comment]
Works like a charm now ;-)

**Comment by hizzlekizzle** [comment]
Awesome. Thanks for testing! I'll promote the edge build to the beta/stable channels and close this issue.
