### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by acc3ssd** [libretro/retroarch-snap#31]
I tried installing Retroarch 1.7.6 via Snap on Ubuntu 18.04back in March and was unable to get audio working. Tonight, I tried installing the latest version on another computer, also running Ubuntu 18.04, and am having the same problem. Stdout gives the following errors:

ALSA lib conf.c:3750:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

Does anyone know what the fix is for this?

**Comment by hizzlekizzle** [comment]
Can you post the output of:
`snap interfaces | grep retroarch`

it should automatically connect the alsa plug, but perhaps that's not happening. Can you try connecting it manually, as per this post:
https://forum.manjaro.org/t/solved-no-sound-in-retroarch-snap/97507

**Comment by acc3ssd** [comment]
Thanks for your help. "snap interfaces | grep retroarch" gives me:

```
:audio-playback            retroarch
:desktop                   retroarch
:home                      retroarch
:joystick                  retroarch
:network                   retroarch
:network-bind              retroarch
:opengl                    retroarch
:raw-usb                   retroarch
:screen-inhibit-control    retroarch
:unity7                    retroarch
:wayland                   retroarch
:x11                       retroarch
-                          retroarch:alsa
-                          retroarch:bluez
-                          retroarch:removable-media
```

After running" sudo snap connect retroarch:alsa" the output looks as follows:

```
:alsa                      retroarch
:audio-playback            retroarch
:desktop                   retroarch
:home                      retroarch
:joystick                  retroarch
:network                   retroarch
:network-bind              retroarch
:opengl                    retroarch
:raw-usb                   retroarch
:screen-inhibit-control    retroarch
:unity7                    retroarch
:wayland                   retroarch
:x11                       retroarch
-                          retroarch:bluez
-                          retroarch:removable-media
```

However, I still have no audio and I am getting the same ALSA errors when I run retroarch. Do you have any other suggestions?

**Comment by hizzlekizzle** [comment]
ok, I just reinstalled my system and had no audio, as well. I tried different audio drivers to no avail, but what seemed to work for me was updating the "core" snap to the "edge" channel. Can you see if that fixes things for you, too?

**Comment by acc3ssd** [comment]
Thanks for the suggestion. Unfortunately, after installing from the edge channel, I still have no audio.

**Comment by hizzlekizzle** [comment]
Is this the one you have?

```
Name  Version                    Rev   Tracking  Publisher   Notes
core  16-2.42.2+git1570.35c66d9  8178  edge      canonical✓  core
```

**Comment by acc3ssd** [comment]
I'm not certain, as I already uninstalled the snap and tried installing via apt. Sorry.

**Comment by hizzlekizzle** [comment]
Closing as the user has worked around the issue.
