### ISSUE TITLE
lubuntu Retroarch 1.8.5 snap don't show external usb drives

### ISSUE THREAD

**Issue by Lucius1202** [libretro/retroarch-snap#33]
With installation from ppa trough my home/media I see every usb drives and set my roms and thumbnails folders here. With snap app the file browser show /media/ empty. The system file manager show all files and folders normally. Thank you.

**Comment by hizzlekizzle** [comment]
try running:
`sudo snap connect retroarch:removable-media`
We have that set up to connect by default, but it apparently doesn't do it anymore for some unknown reason.

**Comment by Lucius1202** [comment]
No problem, now work with your command. I am not a github practitioner, can you mark as solved? I have a question not a issue, but why the interface is too different from classic blue electric "console" look? I search the user interface settings but no pipeline or icons theme options. I download asset, joypad, cheat and every online updatable voice. Thankyou!

**Comment by hizzlekizzle** [comment]
Sure, I'll close the issue.
To change the menu back to the old default, go to settings > driver > menu driver and change it from "ozone" to "xmb".

**Comment by Lucius1202** [comment]
Than you very much! I never find it!
