### ISSUE TITLE
Battery Icon not displaying on Manjaro Linux

### ISSUE THREAD

**Issue by ghost** [libretro/retroarch-snap#35]
Description

On Manjaro Linux, when I load up any menu driver that shows the battery icon, that icon doesn't show up upon having the setting enabled in User Interface
Expected behavior

Battery level appears next to Date and Time
Actual behavior

It only shows Date and Time
Bisect Results

This is after installing Linux on my machine, the battery icon displays fine when I loaded Retroarch on Windows, but not Linux.

My Windows partition currently has Lenovo Vantage installed, with the battery threshold enabled, which appears to still be active even upon booting into Linux.

Going into sys/class/power_supply/BAT/unevent shows this
https://cdn.discordapp.com/attachments/469974542299955210/711661681423679639/Screenshot_from_2020-05-17_12-28-45.png

I believe it is either some dependencies that are missing or Vantage is causing a conflict, though I do not know which one.

#Steps I took

    Confirm Battery level is set to enable in Retroarch
    Confirm if it occurs on battery power or AC (It occurs on both)

Version/Commit

    RetroArch: 1.8.6
    Snap Build: https://snapcraft.io/retroarch

Environment information

    OS: Manjaro Liux 5.6.11.1 Cinnamon
    Compiler: Snap
    Hardware: Lenovo Thinkpad 420
    Other Software: Lenovo Power Vantage (Windows), TLP, ACPI_Call (Linux)

**Comment by hizzlekizzle** [comment]
Have you tried it from any non-snap installations? such as self-compiled or PPA?

**Comment by WandeingLagomorph793** [comment]
> Have you tried it from any non-snap installations? such as self-compiled or PPA?

I'm on Arch Linux so tried the regular package manager version and that one had the exact same issue.

**Comment by hizzlekizzle** [comment]
ok, probably not snap-specific then. That's good news, at least.

**Comment by hizzlekizzle** [comment]
closing since the user doesn't exist anymore
