### ISSUE TITLE
Best way to update Playlists?

### ISSUE THREAD

**Issue by ghost** [libretro/retroarch-snap#36]
Just installed the newest retroarch version via the snap package, is there a good way for me to organize playlists/cores? Cause currently it copied over my files, including my config, but for playlists I have to manually edit them individually, mostly changing the number from 398 to 404, but it still takes awhile when there's a dozen playlists.

**Comment by hizzlekizzle** [comment]
Hmm, i haven't had this problem. I think my playlists are probably using the 'current' symlink instead of hardcoding the version number...?

**Comment by WandeingLagomorph793** [comment]
> Hmm, i haven't had this problem. I think my playlists are probably using the 'current' symlink instead of hardcoding the version number...?

Any places I should check to get to the bottom of it?

**Comment by hizzlekizzle** [comment]
You can check the lpl files themselves, I guess.

**Comment by WandeingLagomorph793** [comment]
> You can check the lpl files themselves, I guess.

That's what I'm doing, I think the issue was it didn't adjust those to the new version number, though I don't know if it's something in the playlists themselves or if it's something with the installation, it adjusted my config file just fine.

**Comment by hizzlekizzle** [comment]
Try replacing the hardcoded version with "current"

**Comment by WandeingLagomorph793** [comment]
> Try replacing the hardcoded version with "current"

It tells me it couldn't find the core, and if I manually add the core it puts the version number in again, unless you mean changing the folder name

**Comment by hizzlekizzle** [comment]
Ah, it worked for mine because it was still set to DETECT. Once it was assigned to a core, it hardcodes the path.

So, it looks like the key is going to be to either find-and-replace the versions or, to do it through the GUI, just go to settings > playlist > manage and then default all associations and then re-associate with the appropriate core.

**Comment by WandeingLagomorph793** [comment]
> Ah, it worked for mine because it was still set to DETECT. Once it was assigned to a core, it hardcodes the path.
> 
> So, it looks like the key is going to be to either find-and-replace the versions or, to do it through the GUI, just go to settings > playlist > manage and then default all associations and then re-associate with the appropriate core. EDIT: or change the playlists to read-only when they're set to DETECT, but then you'll need to choose the core with each launch.

Yeah after an auto update (not sure how many ways there are to disable those from snap) it messed with the cores again, Maybe I can see if there's a solution from mainline Libretro, either natively or maybe some sort of script or tool, but until then I'm gonna try the read only DETECT trick.

**Comment by hizzlekizzle** [comment]
closing, since the user doesn't exist anymore
