### ISSUE TITLE
Not able to Browse

### ISSUE THREAD

**Issue by nothor84** [libretro/retroarch-snap#4]
I have Ubuntu 17.04 (64bits) and once I run Retroarch 1.6.7 and i try to Load Content i can't navigate through the folders, I'm like stuck in "/" but anyway i don't see any folder to enter in.
Do I have to do anything else to navigate through my Hard Drive?

**Comment by hizzlekizzle** [comment]
Hmm, yeah, that's happening here, too, on a fresh system. I don't recall that being an issue on my other system that had previously had RetroArch installed on it, but I can't change the rgui_browser_directory setting in ~/snap/retroarch/10/.config/retroarch/retroarch.cfg to anything outside of its sandbox, and symlinks don't seem to work, either...

Clearly, this needs some work. Thanks for bringing it to our attention!

**Comment by gouchi** [comment]
We already have [home and removable-media interfaces](https://github.com/libretro/retroarch-snap/blob/master/snapcraft.yaml#L12) enabled which give access inside the snap and removable media in  /media and /run/media.

If you need to access outside the snap, I think we will have to enable [udisks2 interface ](https://docs.snapcraft.io/reference/interfaces).

**Comment by gouchi** [comment]
For now you will have to manually connect the interfaces with 
```
sudo snap connect retroarch:home
sudo snap connect retroarch:udisks2
```
If you are only using the home interface, you will have to set `rgui_browser_directory="~"` in the retroarch configuration file located in your home `/home/user/snap/retroarch/current/.config/retroarch.cfg`

**Comment by gouchi** [comment]
Please try again if you reproduced your issue as we updated the package. You should be able to browse your $HOME directory at least.

**Comment by hizzlekizzle** [comment]
You should be able to browse now, with the 'start directory' going to ~/. Feel free to reopen if this doesn't get you fixed up.
