### ISSUE TITLE
Feature request: Split Personality Snap

### ISSUE THREAD

**Issue by loremari** [libretro/retroarch-snap#40]
Just saw this blog post: [https://snapcraft.io/blog/split-personality-snaps](https://snapcraft.io/blog/split-personality-snaps), that mentions a way of creating snaps that can both work as appliances on top of Ubuntu Core and as normal applications ot top of regular Ubuntu Desktop, and wondered if it could apply to RetroArch.

I am currently a Lakka user but would be interested to explore the Ubuntu option for the sake of installing additional services alongside RetroArch (installed on a pc - not a RPI).

**Comment by hizzlekizzle** [comment]
this sounds like a cool thing to do. I've started working on it.
