### ISSUE TITLE
Retroarch Android UI issues

### ISSUE THREAD

**Issue by evildog1** [libretro/retroarch-snap#5]
The icons and switchers disappears. They will appear if you scroll down to the bottom.
My device is TIQ-11003 running Android 5.1.1

![screenshot_2017-10-20-21-25-23](https://user-images.githubusercontent.com/8687585/31839122-ffbf83b6-b5df-11e7-87a0-87e87ee588b8.png)
![screenshot_2017-10-20-21-25-19](https://user-images.githubusercontent.com/8687585/31839118-fc82233e-b5df-11e7-855b-5612372c3fe8.png)

![screenshot_2017-10-20-21-25-01](https://user-images.githubusercontent.com/8687585/31839112-f96a0c98-b5df-11e7-8910-43d99afd30db.png)
![screenshot_2017-10-20-21-24-55](https://user-images.githubusercontent.com/8687585/31839105-f58025e0-b5df-11e7-9a8f-873baffdd16f.png)

**Comment by gouchi** [comment]
You are using snap package on Android ?

**Comment by evildog1** [comment]
I don't know what snap package means. I'm new to Retroarch
I'm sorry if reported the issue in wrong section. I couldn't post issue on forum.

**Comment by gouchi** [comment]
Your [account](https://forums.libretro.com/u/evildog1/summary) is created so you can post on the [forum](https://forums.libretro.com/).

Otherwise please open an issue on the [RA issue tracker](https://github.com/libretro/RetroArch/issues).

Thank you.

**Comment by evildog1** [comment]
Yeah i created an account yesterday but I could not find a way to post a new thread. I'm sure i'm not missing something.
I will just report issues on RA issue tracker instead.
