### ISSUE TITLE
"shm_open failed: 13" error when trying to launch a Playstation game with SwanStation or DuckStation cores (only with the snap version of RetroArch)

### ISSUE THREAD

**Issue by pieqq** [libretro/retroarch-snap#51]
Hello!

The issue has been documented in the [Swanstation core Github repo (Issue #59)](https://github.com/libretro/swanstation/issues/59).

Check [this comment](https://github.com/libretro/swanstation/issues/59#issuecomment-1003842158) for a whole summary/steps/logs.

However, it seems that the problem boils down to the snap package, as the same cores and the same version of RetroArch can be used to load a Playstation game when using the Flatpak and AppImage formats (see [this comment](https://github.com/libretro/swanstation/issues/59#issuecomment-1005098920))

That's too bad, as snaps are quite easy to install on Ubuntu and derivatives.

**Comment by i30817** [comment]
Snap is the devil and i avoid it. 

That said, it seems the snap package doesn't have access to /dev/shm (the 'free memory as a filesystem' idea of linux). I think  hizzlekizzle is currently attempting to fix a similar issue where the snap doesn't have access to the nvidia driver data which is also a 'path'.

**Comment by hizzlekizzle** [comment]
I believe this should be fixed now in the 'edge' channel. I was able to load games in Swanstation, dolphin-libretro and citra-libretro.

**Comment by pieqq** [comment]
I confirm that after switching to the edge channel (retroarch rev1164), I can load a game using the swanstation core! Thanks! \o/

However, I've noticed a problem I didn't have with previous build (not related to this issue, though): the gamepad is "lost" when launching a core, or when going back to the main UI. I have to disconnect/reconnect my controller in order to be able to use it. Should I open an issue about this?

**Comment by hizzlekizzle** [comment]
Hmm, yeah, seems like another issue would be prudent. Be sure to mention whether this issue happens in the 1.9.14 stable build and just happens when you upgrade to the edge channel.

**Comment by gouchi** [comment]
@hizzlekizzle I think we can close this issue.
